[build]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

[functions."*"]
  timeout = 26

[[headers]]
  for = "/downloads/*"
  [headers.values]
    Content-Disposition = "attachment"
