import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
const dir = path.dirname(fileURLToPath(import.meta.url));
const p0 = fs.readFileSync(path.join(dir, 'index.part0.b64'), 'utf8').trim();
const p1 = fs.readFileSync(path.join(dir, 'index.part1.b64'), 'utf8').trim();
const buf = Buffer.concat([Buffer.from(p0, 'base64'), Buffer.from(p1, 'base64')]);
const out = path.resolve(dir, '../../supabase/functions/weekly-plan/index.ts');
fs.writeFileSync(out, buf);
console.log('ORDER8A index materialized', out, buf.length);
